WiFi Connector 2.0
slashdev/loconet-passthrough pull request #5
Opened 2020-01-05 16:46 UTC by jmvdwerf

Most important changes in this feature:

- component Event Handlers uses the new event handling system. A handler can either be registered for a specific event_base (e.g., ```WIFI_EVENT``` or ```IP_EVENT```), or none (```ESP_EVENT_ANY_BASE```). The main loop should register the default event_loop first (i.e., call     ```ESP_ERROR_CHECK( esp_event_loop_create_default() );``` in the ```app_main``` method.

- WifiConnector uses the new IDF event passing system. The component connects to a SSID provided to the station. If no SSID is set, or it cannot connect to the specified AP, it becomes an AP itself.

2020-01-05 20:00 UTC, fuegas requested changes
Good refactor. The names `handlers` and `allHandlers` confuse me though...  Apparently `handlers` is a subset or something? As it isn't described in a comment it's hard to figure out what they are for.

2020-01-05 20:00 UTC, fuegas commented on main/main.cpp
> +    /*
Please remove dead code.

2020-01-05 20:00 UTC, fuegas commented on components/wificonnector/include/wifiap.hpp
> +  void authmode(wifi_auth_mode_t);
Why are you exposing these settings (auth_mode, channel and max_connections)?

2020-01-05 20:00 UTC, fuegas commented on components/wificonnector/include/wifiap.hpp
> +#include "wifibase.hpp"
If the name of a class is "WifiBase", please name the file "wifi_base.cpp".

2020-01-05 20:00 UTC, fuegas commented on components/event_handlers/event_handlers.cpp
> +      // handler was never registered for this event base!
Nitpicking: Please start sentences with a Capital.

2020-01-05 20:00 UTC, fuegas commented on components/event_handlers/event_handlers.cpp
> +  std::list<EventHandler*> allHandlers;
Do you really need to keep a separate list with all handler? For example, using the lists the way you do now, does that cause events to be called twice? You're calling events on `allHandlers` and on `handlers`.

2020-01-05 20:26 UTC, jmvdwerf commented on components/event_handlers/event_handlers.cpp
> +  std::list<EventHandler*> allHandlers;
I renamed ```allHandlers``` to ```genericHandlers```, as it stores a different set of handlers. Also added a comment explaining the difference.

Short summary: handlers can either be registered to a specific ```event_base```, or to ```any```. The former is implemented as the map ```handlers```, the latter as the list ```genericHandlers```.

2020-01-05 20:27 UTC, jmvdwerf commented on components/event_handlers/event_handlers.cpp
> +      // handler was never registered for this event base!
Fixed!

2020-01-05 20:38 UTC, jmvdwerf reviewed
Done!

2020-01-05 20:38 UTC, jmvdwerf commented on components/wificonnector/include/wifiap.hpp
> +#include "wifibase.hpp"
Done!

2020-01-05 20:38 UTC, jmvdwerf commented on components/wificonnector/include/wifiap.hpp
> +  void authmode(wifi_auth_mode_t);
The main reason is that I don't know yet who will "own" the settings, and where and how these are stored and retrieved. If that will be the task of this component as well, it is not required to expose any of them anymore.

2020-01-05 20:38 UTC, jmvdwerf commented on main/main.cpp
> +    /*
Done!

2020-01-05 22:57 UTC, fuegas approved these changes
I'll approve the code as I do not see big flaws in it. But please process the comments into a new PR.

2020-01-05 22:57 UTC, fuegas commented on components/event_handlers/event_handlers.cpp
> +
Nitpick: Leftover whitespace.

2020-01-05 22:57 UTC, fuegas commented on components/event_handlers/include/event_handlers.hpp
> +  void init();
Nitpick: Please use `void init(void);`

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/CMakeLists.txt
> +        "wifi_base.cpp"
Nitpick: Please use 2 spaces for indentation.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/CMakeLists.txt
> +        event_handlers
Nitpick: ditto.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/include/wifi_ap.hpp
> +
Nitpick: Double newline.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/include/wifi_connector.hpp
> +
Nitpick: These includes are our own code, so this newline isn't needed.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_ap.cpp
> +  this->max_connections(4);
Is there a reason to limit the number of allowed connections to a AP?

If there is no need to be able to change it later, you can set it directly in the config above as well.
```c++
cfg_ap_.ap.max_connection = 4;
```

Then the whole maxconnections method can be removed I guess?

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_ap.cpp
> +    ssid_ = "";
Is an empty string a correct fallback if the given string is longer than 32 chars? Would a neater solution be to create an AP with the allowed length of the provided SSID?

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_ap.cpp
> +  }
If the SSID is too long, you set it to `""`, for the password there is no fallback behaviour, is this intended? What happens if the password is too long? Do we have a public (non-password-protected) AP then?

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_connector.cpp
> +#include "event_handlers.hpp"
Nitpick: Please order lexicographically.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_station.cpp
> +
Nitpick: This newline can be removed, and the includes ordered lexicographically.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_station.cpp
> +    ssid_ = "";
Same question here as at the SSID of the AP code.

2020-01-05 22:57 UTC, fuegas commented on components/wifi_connector/wifi_station.cpp
> +  }
Same question here as at the password of the AP code.

2020-01-07 16:23 UTC, jmvdwerf reviewed
I made the changes as you requested. Password and SSID are now capped at 32 and 64, resp. if they are too long.

2020-01-10 22:08 UTC, merged