httpd server
slashdev/loconet-passthrough pull request #8
Opened 2020-01-17 21:01 UTC by jmvdwerf

This branch provides a simple httpd server. It uses the lwip implementation to listen for connections. Note that this is a FreeRTOS implementation of lwip.

The basic idea is that the server listens for connections (```processAccept```), and on a new connection, it creates a session object, that needs to be processed (```processSession```). In principle, these tasks could be assigned to different FreeRTOS tasks. For simplicity, the method ```thread``` combines both calls.

On a non-empty session, the server checks all registered ```RequestHandler```s. The first that ```accept```s the RequestHandler will handle the session, by writing to the ```Response``` object that is provided in the method call ```handle```. If no RequestHandler accepts the session, a default error message is written.

For inclusion in the main.cpp, a simple task manager is written. This script ensures that when ```httpd_server_initialize(stacksize, priority)``` is called in the ```app_main``` method, the webserver is initialized, and started as soon as the device gets an ip address. 

Note that currently it waits until a WIFI_EVENT or IP_EVENT is raised before the system starts. It does not check whether the device already has an IP-address.

2020-01-17 22:25 UTC, fuegas requested changes
Please keep an eye on the whitespace usage, the newlines look quite random if you compare the usage in the files. 

When you're going to apply the suggestions, please use the "Add suggestion to batch" button and process them in a single commit :smile:.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    // ESP_LOGI("Request", "I have uri: %s", uri_.c_str());
Either change to `ESP_LOGD` or `ESP_LOGV` or remove  this line.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    // ESP_LOGI("Request", "I have method: '%s'", std::string(data, cursor).c_str());
Either change to `ESP_LOGD` or `ESP_LOGV` or remove  this line.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    cursor = parseHeaders(cursor );
```suggestion
    cursor = parseHeaders(cursor);
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    // at least one \n, so we remove that one as well.
Where do you remove it? Because I only see a `std::string` init, no removal.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    char* end = cursor;
```suggestion
    char *end = cursor;
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +      char* endofline = std::strstr(begin, "\r\n");
```suggestion
      char *endOfLine = std::strstr(begin, "\r\n");
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +      if (!endofline)
```suggestion
      if (!endOfLine)
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +      else if (endofline == begin)
```suggestion
      else if (endOfLine == begin)
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +      char* colon = std::strstr(begin, ":");
```suggestion
      char *colon = std::strstr(begin, ":");
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +      char* begin = var;
```suggestion
      char *begin = var;
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    char* var = data;
```suggestion
    char *var = data;
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    char* end = begin;
```suggestion
    char *end = begin;
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +    // first remove trailing spaces
```suggestion
    // Remove spaces at the start of the URI
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.cpp
> +  std::string Request::toString(method::eHTTPMethod_t code)
If you convert a Request to string, I'd expect more than the string version of the method. Can you rename the function to `methodToString` or something similar?

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request_handler.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/response.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/response.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/response.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +  Server::Server() : Server(80)
Please keep the constructors together. Between the constructors is a destructor now.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +      // ESP_LOGE(TAG, "NO SOCKET");
Remove dead code or lower the importance of the log level.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +      if( !session->process() )
```suggestion
      if(!session->process())
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +      if (!handled)
```suggestion

      if (!handled)
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +      // ESP_LOGD(TAG, "NO SOCKET");
Remove dead code or lower the log level.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +    // Snd the same time out for sending
```suggestion
    // Set the same timeout for sending
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.cpp
> +    // Set recv timeout of this fd
```suggestion
    // Set receive timeout of this fd
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/server.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/response.hpp
> +  private:
```suggestion

  private:
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/request.hpp
> +  protected:
```suggestion

  protected:
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.cpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.cpp
> +    if (request_ != NULL) delete request_;
Always use curlies please.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.cpp
> +     int len = recv(socket_, buffer, sizeof(buffer) - 1, 0);
Different indentation than lines above.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.hpp
> +	class Session
Different indentation than other files, please use 2 spaces for each indent level everywhere.

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.hpp
> +	private:
```suggestion

	private:
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/session.hpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd/util/uri.cpp
> +
```suggestion
```

2020-01-17 22:25 UTC, fuegas commented on components/httpd_server/src/httpd_server_task.cpp
> +      httpd_server_stop();
Does it really need to be stopped if the wifi disconnects?

2020-01-17 22:25 UTC, fuegas commented on components/wifi_httpdhandler/src/wifihandler/handler.cpp
> +    namespace wifi
If the component is named `wifihandler` (or should that be `wifi_handler`?), why is the namespace `httpd::handlers::wifi`, that does not match.

2020-01-17 22:25 UTC, fuegas commented on components/wifi_httpdhandler/src/wifihandler/handler.hpp
> +      private:
```suggestion

      private:
```

2020-01-17 22:25 UTC, fuegas commented on components/wifi_httpdhandler/src/wifihandler/handler.cpp
> +
```suggestion
```

2020-01-18 20:06 UTC, jmvdwerf reviewed
All requests have been processed, the source compiles and runs on the device.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/request.cpp
> +    // ESP_LOGI("Request", "I have method: '%s'", std::string(data, cursor).c_str());
Changed it everywhere to ESP_LOGD

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/request.cpp
> +    // ESP_LOGI("Request", "I have uri: %s", uri_.c_str());
Changed

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/request.cpp
> +    // at least one \n, so we remove that one as well.
Actually, already in ```parseHeaders```. I removed the comment.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/request.cpp
> +  std::string Request::toString(method::eHTTPMethod_t code)
done.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/server.cpp
> +  Server::Server() : Server(80)
Done.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/server.cpp
> +      // ESP_LOGE(TAG, "NO SOCKET");
Removed.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/server.cpp
> +      // ESP_LOGD(TAG, "NO SOCKET");
Removed.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/session.cpp
> +    if (request_ != NULL) delete request_;
Done.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/session.cpp
> +     int len = recv(socket_, buffer, sizeof(buffer) - 1, 0);
Updated.

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd/session.hpp
> +	class Session
Check!

2020-01-18 20:06 UTC, jmvdwerf commented on components/httpd_server/src/httpd_server_task.cpp
> +      httpd_server_stop();
The problem is that if the IP address changes, the socket implementation of lwip crashes. To be sure, I stop the server as soon as the connection is dropped, and by restarting the server upon reconnecting, a new tcp socket is opened.

2020-01-18 20:06 UTC, jmvdwerf commented on components/wifi_httpdhandler/src/wifihandler/handler.cpp
> +    namespace wifi
Renamed the namespace to wificonfigurator.

2020-01-18 20:11 UTC, fuegas approved these changes

2020-01-18 20:41 UTC, merged